# ============================================================================
#  kitty — terminal
#  Recargar sin cerrar: Ctrl+Shift+F5       Referencia: https://sw.kovidgoyal.net/kitty/conf/
# ============================================================================

font_family      JetBrainsMono Nerd Font
font_size        11.5

window_padding_width 12
# Transparencia: Niri desenfoca lo que hay detrás (rules.kdl)
background_opacity   0.82
confirm_os_window_close 0
enable_audio_bell no
cursor_shape beam
cursor_trail 1

# Pestañas
tab_bar_edge      bottom
tab_bar_style     powerline
tab_powerline_style slanted

# --- Colores: interfaz en blanco (tema "blanco") ----------------------------
foreground              #e5e9f0
background              #1a1b1e
selection_foreground    #1a1b1e
selection_background    #e5e9f0
cursor                  #ffffff
cursor_text_color       #1a1b1e
url_color               #ffffff

active_tab_foreground   #1a1b1e
active_tab_background   #e5e9f0
inactive_tab_foreground #8a8f98
inactive_tab_background #26272b
tab_bar_background      #1a1b1e

# --- Los 16 colores de la terminal: Nord (ls, git, etc. los necesitan) ----

# negro
color0  #3b4252
color8  #4c566a
# rojo
color1  #bf616a
color9  #bf616a
# verde
color2  #a3be8c
color10 #a3be8c
# amarillo
color3  #ebcb8b
color11 #ebcb8b
# azul
color4  #81a1c1
color12 #81a1c1
# magenta
color5  #b48ead
color13 #b48ead
# cian
color6  #88c0d0
color14 #8fbcbb
# blanco
color7  #e5e9f0
color15 #eceff4
